myProps:
  title: 康元佳
  description: 好好学习天天向上
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    druid:
      first:
        url: jdbc:mysql://localhost:3306/test?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
        username: root
        password: kyj123
      second:
        url: jdbc:mysql://127.0.0.1:3306/monitor?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
        username: root
        password: kyj123
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          auto: update
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: null
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        min-idle: 0
        max-idle: 8
mybatis:
  type-aliases-package: com.kyj.demo.entity
  mapper-locations: classpath:mybatis/mapper/*.xml